In [ ]:
import yfinance as yf 
import pandas as pd
from IPython.display import display

aapl = yf.Ticker("AAPL")
df = aapl.financials

display(df)

,2025-09-30,2024-09-30,2023-09-30,2022-09-30,2021-09-30
Tax Effect Of Unusual Items,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,NaN
Tax Rate For Calcs,1.560000e-01,2.410000e-01,1.470000e-01,1.620000e-01,NaN
Normalized EBITDA,1.447480e+11,1.346610e+11,1.258200e+11,1.305410e+11,NaN
Net Income From Continuing Operation Net Minority Interest,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Reconciled Depreciation,1.169800e+10,1.144500e+10,1.151900e+10,1.110400e+10,NaN
Reconciled Cost Of Revenue,2.209600e+11,2.103520e+11,2.141370e+11,2.235460e+11,NaN
EBITDA,1.447480e+11,1.346610e+11,1.258200e+11,1.305410e+11,NaN
EBIT,1.330500e+11,1.232160e+11,1.143010e+11,1.194370e+11,NaN
Net Interest Income,NaN,NaN,-1.830000e+08,-1.060000e+08,1.980000e+08
Interest Expense,NaN,NaN,3.933000e+09,2.931000e+09,2.645000e+09
Interest Income,NaN,NaN,3.750000e+09,2.825000e+09,2.843000e+09
Normalized Income,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Net Income From Continuing And Discontinued Operation,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Total Expenses,2.831110e+11,2.678190e+11,2.689840e+11,2.748910e+11,NaN
Total Operating Income As Reported,1.330500e+11,1.232160e+11,1.143010e+11,1.194370e+11,NaN
Diluted Average Shares,1.500470e+10,1.540810e+10,1.581255e+10,1.632582e+10,NaN
Basic Average Shares,1.494850e+10,1.534378e+10,1.574423e+10,1.621596e+10,NaN
Diluted EPS,7.460000e+00,6.080000e+00,6.130000e+00,6.110000e+00,NaN
Basic EPS,7.490000e+00,6.110000e+00,6.160000e+00,6.150000e+00,NaN
Diluted NI Availto Com Stockholders,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Net Income Common Stockholders,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Net Income,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Net Income Including Noncontrolling Interests,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Net Income Continuous Operations,1.120100e+11,9.373600e+10,9.699500e+10,9.980300e+10,NaN
Tax Provision,2.071900e+10,2.974900e+10,1.674100e+10,1.930000e+10,NaN
Pretax Income,1.327290e+11,1.234850e+11,1.137360e+11,1.191030e+11,NaN
Other Income Expense,-3.210000e+08,2.690000e+08,-5.650000e+08,-3.340000e+08,NaN
Other Non Operating Income Expenses,-3.210000e+08,2.690000e+08,-5.650000e+08,-3.340000e+08,NaN
Net Non Operating Interest Income Expense,NaN,NaN,-1.830000e+08,-1.060000e+08,1.980000e+08
Interest Expense Non Operating,NaN,NaN,3.933000e+09,2.931000e+09,2.645000e+09
Interest Income Non Operating,NaN,NaN,3.750000e+09,2.825000e+09,2.843000e+09
Operating Income,1.330500e+11,1.232160e+11,1.143010e+11,1.194370e+11,NaN
Operating Expense,6.215100e+10,5.746700e+10,5.484700e+10,5.134500e+10,NaN
Research And Development,3.455000e+10,3.137000e+10,2.991500e+10,2.625100e+10,NaN
Selling General And Administration,2.760100e+10,2.609700e+10,2.493200e+10,2.509400e+10,NaN
Gross Profit,1.952010e+11,1.806830e+11,1.691480e+11,1.707820e+11,NaN
Cost Of Revenue,2.209600e+11,2.103520e+11,2.141370e+11,2.235460e+11,NaN
Total Revenue,4.161610e+11,3.910350e+11,3.832850e+11,3.943280e+11,NaN
Operating Revenue,4.161610e+11,3.910350e+11,3.832850e+11,3.943280e+11,NaN

In [ ]:
aapl = yf.Ticker("AAPL")
prices = aapl.history(period="5y")
eps = aapl.financials.loc["Diluted EPS"]

pe_history = []

for date, eps_value in eps.items():
    if pd.isna(eps_value):
        continue
    
    year = date.year
    year_prices = prices.loc[prices.index.year == year]
    if not year_prices.empty and eps_value and eps_value != 0:
        price = year_prices.loc["Close"].iloc[-1]
        pe = round(price / eps_value , 2)
        pe_history.append({"year": str(year), "pe": pe})
        






display(eps)

2025-09-30    7.46
2024-09-30    6.08
2023-09-30    6.13
2022-09-30    6.11
2021-09-30     NaN
Name: Diluted EPS, dtype: float64

In [227]:
display(aapl.history(period="5y"))

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2021-06-28 00:00:00-04:00,130.041639,131.835179,129.983157,131.377045,62111300,0.0,0.0
2021-06-29 00:00:00-04:00,131.396555,133.043888,130.957920,132.887924,64556100,0.0,0.0
2021-06-30 00:00:00-04:00,132.731982,133.940680,132.439554,133.502045,63261400,0.0,0.0
2021-07-01 00:00:00-04:00,133.151087,133.862651,132.332284,133.804169,52485800,0.0,0.0
2021-07-02 00:00:00-04:00,134.418283,136.465268,134.272077,136.426285,78852600,0.0,0.0
...,...,...,...,...,...,...,...
2026-06-22 00:00:00-04:00,297.309998,302.420013,296.760010,297.010010,44879900,0.0,0.0
2026-06-23 00:00:00-04:00,297.540009,301.640015,294.179993,294.299988,52010900,0.0,0.0
2026-06-24 00:00:00-04:00,295.359985,299.700012,292.940002,293.079987,53081900,0.0,0.0
2026-06-25 00:00:00-04:00,287.399994,288.799988,273.750000,275.149994,107013700,0.0,0.0
2026-06-26 00:00:00-04:00,275.000000,285.950012,274.209991,283.779999,261693600,0.0,0.0

In [ ]:
data = {
    "Name":["Joel", "Sam", "Matthew"],
    "Age": [19, 20, 25]
    }
df = pd.DataFrame(data, index=["person1", "person2", "person3"])
df["Job"] = ["SWE", "DJ", "CEO" ]

new_rows = pd.DataFrame([{"Name": "Ruben", "Age": 35, "Job": "Engineer"}, {"Name": "Andrew", "Age": 35, "Job": "Quant"}], index=["person4", "person5"])
df = pd.concat([df, new_rows])

                              


display(df)

            Name  Age       Job
person1     Joel   19       SWE
person2      Sam   20        DJ
person3  Matthew   25       CEO
person4    Ruben   35  Engineer
person5   Andrew   35     Quant

In [223]:
data2 = [[1,2,3], [4,5,6]]
data3 = { 0:[1,2,3], 1: [4,5,6]}
display(pd.DataFrame(data2))
display(pd.DataFrame(data3))

display(pd.DataFrame(data3).iloc[1])

   0  1  2
0  1  2  3
1  4  5  6

   0  1
0  1  4
1  2  5
2  3  6

0    2
1    5
Name: 1, dtype: int64