In [67]:
stock = yf.Ticker("XLK")
data = stock.history(period="1d", interval="1m")

display(data)

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Capital Gains
Datetime,,,,,,,,
2026-07-02 09:30:00-04:00,185.490005,185.509995,184.710007,185.300003,326246,0.0,0.0,0.0
2026-07-02 09:31:00-04:00,185.250000,185.449997,185.000000,185.145004,59837,0.0,0.0,0.0
2026-07-02 09:32:00-04:00,185.229996,185.619995,185.190002,185.270004,44242,0.0,0.0,0.0
2026-07-02 09:33:00-04:00,185.289993,185.479996,185.119995,185.369995,47190,0.0,0.0,0.0
2026-07-02 09:34:00-04:00,185.460007,185.940002,185.460007,185.889999,44632,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
2026-07-02 15:55:00-04:00,180.320007,180.320007,180.039993,180.220001,153074,0.0,0.0,0.0
2026-07-02 15:56:00-04:00,180.220001,180.345001,180.210007,180.330002,116689,0.0,0.0,0.0
2026-07-02 15:57:00-04:00,180.309998,180.485001,180.279999,180.460007,124035,0.0,0.0,0.0
2026-07-02 15:58:00-04:00,180.464996,180.619995,180.440002,180.580002,180000,0.0,0.0,0.0
2026-07-02 15:59:00-04:00,180.589996,180.699997,180.300003,180.520004,564637,0.0,0.0,0.0

In [41]:
print(list(yf.PREDEFINED_SCREENER_QUERIES.keys()))

['aggressive_small_caps', 'day_gainers', 'day_losers', 'growth_technology_stocks', 'most_actives', 'most_shorted_stocks', 'small_cap_gainers', 'undervalued_growth_stocks', 'undervalued_large_caps', 'conservative_foreign_funds', 'high_yield_bond', 'portfolio_anchors', 'solid_large_growth_funds', 'solid_midcap_growth_funds', 'top_mutual_funds', 'top_etfs_us', 'top_performing_etfs', 'technology_etfs', 'bond_etfs']

In [ ]:
import yfinance as yf 
import pandas as pd
from IPython.display import display


stock = yf.Ticker("^JKSE")

display(stock.info)

{'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 5744.556,
 'open': 5806.167,
 'dayLow': 5805.922,
 'dayHigh': 5899.302,
 'regularMarketPreviousClose': 5744.556,
 'regularMarketOpen': 5806.167,
 'regularMarketDayLow': 5805.922,
 'regularMarketDayHigh': 5899.302,
 'volume': 0,
 'regularMarketVolume': 0,
 'averageVolume': 314554589,
 'averageVolume10days': 175068240,
 'averageDailyVolume10Day': 175068240,
 'bid': 0.0,
 'ask': 0.0,
 'bidSize': 0,
 'askSize': 0,
 'fiftyTwoWeekLow': 5317.908,
 'fiftyTwoWeekHigh': 9174.474,
 'allTimeHigh': 9174.474,
 'allTimeLow': 223.249,
 'fiftyDayAverage': 6450.3105,
 'twoHundredDayAverage': 7741.955,
 'currency': 'IDR',
 'tradeable': False,
 '52WeekChange': -14.855271,
 'quoteType': 'INDEX',
 'symbol': '^JKSE',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Index',
 'quoteSourceName': 'Delayed Quote',
 'triggerable': False,
 'customPriceAlertConfidence': 'LOW',
 'exchange': 'JKT',
 'messageBoardId': 'finmb_INDEXJKSE',
 'exchangeTimezoneName': 'Asia/Jakarta',
 'exchangeTimezoneShortName': 'WIB',
 'gmtOffSetMilliseconds': 25200000,
 'market': 'id_market',
 'esgPopulated': False,
 'marketState': 'CLOSED',
 'longName': 'IDX COMPOSITE',
 'hasPrePostMarketData': False,
 'firstTradeDateMilliseconds': 639367200000,
 'regularMarketChange': 131.22363,
 'regularMarketDayRange': '5805.922 - 5899.302',
 'fullExchangeName': 'Jakarta',
 'averageDailyVolume3Month': 314554589,
 'fiftyTwoWeekLowChange': 557.8716,
 'fiftyTwoWeekLowChangePercent': 0.104904324,
 'fiftyTwoWeekRange': '5317.908 - 9174.474',
 'fiftyTwoWeekHighChange': -3298.6938,
 'fiftyTwoWeekHighChangePercent': -0.35955128,
 'fiftyTwoWeekChangePercent': -14.855271,
 'fiftyDayAverageChange': -574.53076,
 'fiftyDayAverageChangePercent': -0.089070246,
 'twoHundredDayAverageChange': -1866.1753,
 'twoHundredDayAverageChangePercent': -0.24104702,
 'sourceInterval': 10,
 'exchangeDataDelayedBy': 10,
 'cryptoTradeable': False,
 'corporateActions': [],
 'regularMarketTime': 1783069205,
 'shortName': 'IDX COMPOSITE',
 'regularMarketChangePercent': 2.2843127,
 'regularMarketPrice': 5875.78,
 'trailingPegRatio': None}

In [36]:
data = {
    "Name":["Joel", "Sam", "Matthew"],
    "Age": [19, 20, 25]
    }
df = pd.DataFrame(data, index=["person1", "person2", "person3"])
df["Job"] = ["SWE", "DJ", "CEO" ]

new_rows = pd.DataFrame([{"Name": "Ruben", "Age": 35, "Job": "Engineer"}, {"Name": "Andrew", "Age": 35, "Job": "Quant"}], index=["person4", "person5"])
df = pd.concat([df, new_rows])

                              


display(df)

            Name  Age       Job
person1     Joel   19       SWE
person2      Sam   20        DJ
person3  Matthew   25       CEO
person4    Ruben   35  Engineer
person5   Andrew   35     Quant

In [37]:
data2 = [[1,2,3], [4,5,6]]
data3 = { 0:[1,2,3], 1: [4,5,6]}
display(pd.DataFrame(data2))
display(pd.DataFrame(data3))

display(pd.DataFrame(data3).iloc[1])

   0  1  2
0  1  2  3
1  4  5  6

   0  1
0  1  4
1  2  5
2  3  6

0    2
1    5
Name: 1, dtype: int64